import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import ModeToggle from "@/app/components/modeToggle";
import Navbar from "@/app/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hikaru's Domain",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-[#212529] text-black dark:text-white transition duration-500`}
    >

      <main className="px-8 md:px-24 lg:px-72">
        {/* Navbar */}
        <nav
          className="fixed w-full md:w-auto left-0 top-0 md:top-5 md:left-1/2 md:-translate-x-1/2 text-white bg-[#495057] shadow-md px-7 py-3 md:rounded-full flex gap-4 md:gap-[92px] items-center font-medium backdrop-blur-sm z-50"
        >
          <h1 className="flex-2 text-xl font-bold h-7 w-auto md:w-44 items-center justify-center cursor-default">
            Hikaru&apos;s Domain
          </h1>

          <Navbar />

          <div className="hidden md:block">
            <ModeToggle />
          </div>
        </nav>

        {/* Main Content */}
        {children}

        <footer className="fixed sm:-left-1 left-0 bottom-0 w-full items-center justify-center text-center text-sm text-neutral-500 bg-[#212529]">
          2025 Copyright Hikaru
        </footer>
      </main>

    </body>
    </html>
  );
}
